import "./globals.css";
import { Toaster } from "sonner";
import { Nunito } from "next/font/google";
import { AuthProvider } from "@/app/context/auth-context";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "PictoFest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Toaster richColors position="top-right" />
        </AuthProvider>
      </body>
    </html>
  );
}
