import "./globals.css";
import { Toaster } from "sonner";
import { Nunito } from "next/font/google";
import { AuthProvider } from "@/app/context/Auth";

const inter = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "PictoFest Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          {children}
          <Toaster
            position="top-right"
            richColors
            closeButton
            duration={4000}
            pauseWhenPageIsHidden
            visibleToasts={1}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
